---
- name: Converge
  hosts: all
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "hacker"
        shell: /bin/bash
        create_home: true

    - name: "Include ansible-role-burpsuite"
      ansible.builtin.include_role:
        name: "ansible-role-burpsuite"
