---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: kali-burpsuite
    image: kalilinux/kali-rolling
    volumes:
      - ~/Downloads/burpsuite_community_linux_v2020_2.sh:/tmp/burpsuite_community_linux_v2020_2.sh:ro
    groups:
      - community
provisioner:
  name: ansible
  inventory:
    group_vars:
      community:
        burpsuite_user: hacker
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    v: true
  lint:
    name: flake8
