---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kali-burpsuite
    image: kalilinux/kali-rolling
    groups:
      - community
provisioner:
  name: ansible
  inventory:
    group_vars:
      community:
        burpsuite_user: hacker
verifier:
  name: ansible
  options:
    v: true

