---
# Playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Install python3-lxml
    ansible.builtin.apt:
      name: python3-lxml
      state: present

  - name: Check Burp Suite prefs.xml file
    ansible.builtin.stat:
      path: /home/hacker/.java/.userPrefs/burp/prefs.xml
    register: prefs_file

  - name: Assert that file exists and is a regular file
    ansible.builtin.assert:
      that:
        - prefs_file.stat.exists
        - prefs_file.stat.isreg

  - name: Count eula entries
    ansible.builtin.xml:
      path: /home/hacker/.java/.userPrefs/burp/prefs.xml
      xpath: /map/entry[@key='eulacommunity']
      count: true
    register: prefs_eula_count

  - name: Count caCert entries
    ansible.builtin.xml:
      path: /home/hacker/.java/.userPrefs/burp/prefs.xml
      xpath: /map/entry[@key='caCert']
      count: true
    register: prefs_cacert_count

  - name: Assert eula entry exists
    ansible.builtin.assert:
      that:
        - prefs_eula_count.count > 0

  - name: Assert caCert entry exists
    ansible.builtin.assert:
      that:
        - prefs_cacert_count.count > 0
